# Generated by Django 5.2.12 on 2026-04-03 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('GRAMMAR', 'Grammar'), ('LISTENING', 'Listening'), ('SPEAKING', 'Speaking')], max_length=20)),
                ('question_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='assessment/audio/')),
                ('correct_answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grammar_score', models.FloatField(default=0)),
                ('listening_score', models.FloatField(default=0)),
                ('speaking_score', models.FloatField(default=0)),
                ('overall_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('audio_answer', models.FileField(blank=True, null=True, upload_to='assessment/response')),
                ('score', models.FloatField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
