# Generated by Django 5.2.12 on 2026-04-28 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenzLingo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(max_length=255, unique=True)),
                ('meaning', models.TextField()),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('tone', models.TextField(choices=[('FUNNY', 'Funny'), ('CASUAL', 'Casual'), ('SARCASTIC', 'Sarcastic'), ('POSITIVE', 'Positive')], default='CASUAL')),
                ('popularity_level', models.TextField(choices=[('TRENDING', 'Trending'), ('COMMON', 'Common'), ('RARE', 'Rare')], default='COMMON')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'genz_lingo',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField(unique=True)),
                ('meaning', models.TextField()),
                ('literal_meaning', models.TextField(blank=True, null=True)),
                ('usage_context', models.TextField(blank=True, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('category', models.TextField(choices=[('MOTIVATION', 'Motivation'), ('REALITY', 'Reality'), ('BUSINESS', 'Business'), ('HUMOR', 'Humor'), ('DAILY_LIFE', 'Daily Life')], default='DAILY_LIFE')),
                ('difficulty_level', models.TextField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phrases',
                'ordering': ['phrase'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True)),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('meaning', models.TextField()),
                ('part_of_speech', models.CharField(blank=True, choices=[('NOUN', 'Noun'), ('VERB', 'Verb'), ('ADJECTIVE', 'Adjective'), ('ADVERB', 'Adverb'), ('PRONOUN', 'Pronoun'), ('PREPOSITION', 'Preposition'), ('CONJUNCTION', 'Conjunction'), ('INTERJECTION', 'Interjection')], max_length=50, null=True)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('difficulty_level', models.TextField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER')),
                ('category', models.TextField(choices=[('BUSINESS', 'Business'), ('DAILY_LIFE', 'Daily Life'), ('TRAVEL', 'Travel'), ('TECHNOLOGY', 'Technology'), ('ACADEMIC', 'Academic'), ('GENERAL', 'General')], default='GENERAL')),
                ('source_type', models.TextField(default='manual')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vocabulary_words',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='DailyVocabularyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_vocab_contents', to=settings.AUTH_USER_MODEL)),
                ('genz_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.genzlingo')),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.phrase')),
                ('vocabulary_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocabulary.vocabularyword')),
            ],
            options={
                'db_table': 'daily_vocabulary_content',
                'ordering': ['-delivered_date'],
                'unique_together': {('user', 'delivered_date')},
            },
        ),
    ]
